#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require 'fileutils'

root_dir = File.expand_path('../', File.dirname(__FILE__))
pid_dir = root_dir + '/tmp/pids'
log_dir = root_dir + '/log'
FileUtils.mkdir_p(pid_dir)
FileUtils.mkdir_p(log_dir)

def exception_to_str(e)
  e.message + "\n" + e.backtrace.join("\n        from ")
end

# for some reason, log_output doesn't seem to work. Oh well..
Daemons.run_proc('background_daemon', dir_mode: :normal, dir: pid_dir, log_dir: log_dir, log_output: false) do
  Dir.chdir root_dir
  require root_dir + '/config/environment'
  if Rails.logger.respond_to? :auto_flushing=
    Rails.logger.auto_flushing = true
  end

  loop do
    BackgroundTaskRegistry.all_tasks.each do |task|
      begin
        task.run
      rescue => e
        Rails.logger.error "#{task.class.name} exception: " + exception_to_str(e)

        begin
          ActiveRecord::Base.verify_active_connections!
        rescue => e2
          Rails.logger.error 'Failed to verify DB connection: ' + exception_to_str(e2)
        end
      end
    end

    sleep 0.1
  end
end
